drop table if exists account CASCADE;

    create table account (
       id bigint generated by default as identity,
        accountType varchar(255),
        uniqueUserId varchar(255),
        url varchar(255),
        userName varchar(255),
        primary key (id)
    );

