drop table if exists user_presonal_details CASCADE;

create table user_presonal_details (
--       id BIGSERIAL primary key,
       id int generated by default as identity (start with 1) primary key,
        first_name varchar(255) not null,
        last_name varchar(255),
        uniqueId varchar(255)
    );
--create table user_presonal_details (
--       id BIGSERIAL primary key,
--        created timestamp,
--        created_by varchar(255),
--        updated timestamp,
--        updated_by varchar(255),
--        first_name varchar(255) not null,
--        last_name varchar(255),
--        uniqueId varchar(255)
--    )
    
-- "Str" on using doubleqoutes gets error, use only singlequotes
--insert into user_presonal_details (first_name, last_name, uniqueId) values ('Yash', 'M', 'Test_777');
insert into user_presonal_details (id, first_name, last_name, uniqueId) values (1, 'Yash', 'M', 'Test_777');